name: Tests

on:
  pull_request:
    paths:
      - '**.py'
      - 'requirements.txt'
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: make deps

    - name: Run tests
      run: make test
